apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejokimapp
  labels:
    app: sejokimapp
spec:
  selector:
    matchLabels:
      app: sejokimapp
  templates:
    metadata:
      labels:
        app: sejokimapp
    spec:
      containers:
      - name: sejokimapp
        image: wil42/playground:v1
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: sejokimapp
spec:
  selector:
    app: sejokimapp
  ports:
    - protocol: TCP
      port: 4242
      targetPort: 8888