apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejokimapp
  namespace: dev
  labels:
    app: sejokimapp
spec:
  selector:
    matchLabels:
      app: sejokimapp
  template:
    metadata:
      labels:
        app: sejokimapp
    spec:
      containers:
      - name: sejokimapp
        image: wil42/playground:v2
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: service-sejokimapp
  namespace: dev
spec:
  type: NodePort
  selector:
    app: sejokimapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8888